# FIMD 测试：seed3407 vessel_only_masked w=0.1
FIMD:
  data_root: /home/data1/zhangjunhong/sr_project/sr/data/FIMD

PREDICT:
  device: cuda:1

  model_save_path: /home/data1/zhangjunhong/sr_project/sr/save/seed3407_vessel_masked_w01_ep149.pth
  model_type: with_vessel_only_masked

  resize_refer_to_query: true

  model_image_width: 768
  model_image_height: 768
  use_matching_trick: True

  registration_method: 'quadratic'
  displacement_threshold: 300.0

  nms_size: 10
  nms_thresh: 0.01
  knn_thresh: 0.9

  use_inverse_consistency: True
  iccl: 3.0

  use_outlier_filter: True
  outlier_criteria: 'homography'
  outlier_threshold: 20.0

  eye_mask_path: null

  checkerboard_tile_size: 240
