MODEL:
  model_variant: vessel_only_masked
  nms_size: 10
  nms_thresh: 0.1

  batch_size: 4
  num_epoch: 150
  seed: 3407
  deterministic: true
  num_workers: 8

  device: cuda:0
  load_pre_trained_model: false
  pretrained_path: /home/data1/zhangjunhong/sr_project/sr/save/model_6.pth
  resume_optimizer: false

  model_save_path: /home/data1/zhangjunhong/sr_project/sr/save/seed3407_vessel_masked_w01_ep149.pth
  model_save_epoch: 1

  perceptual_weight: 0.05
  perceptual_start_epoch: 0

  vessel_weight: 0.1

  vessel_mask_backend: morph
  vessel_mask_threshold: 0.25
  vessel_mask_dilate: 3

  memory_fraction: 0.9

DATASET:
  model_image_width: 768
  model_image_height: 768
  dataset_path: /home/data1/zhangjunhong/sr_project/sr/data/Lab4
  train_split_file: train.txt
  val_split_file: val.txt
  auxiliary: /home/data1/zhangjunhong/sr_project/sr/data/Auxiliary

PKE:
  pke_start_epoch: 0
  geometric_thresh: 0.5
  content_thresh: 0.7
  gaussian_kernel_size: 13
  gaussian_sigma: 2

  pke_show: false
  pke_show_epoch: 5
  pke_show_list: []

VALUE_MAP:
  area: 8
  value_increase_point: 5
  value_increase_area: 1
  value_decay: 1
  is_value_map_save: true
  resume_value_map: false
  value_map_save_dir: /home/data1/zhangjunhong/sr_project/sr/data/seed3407_vessel_masked_w01_value_maps
